variables:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: 984310022655
  LINODE_FIREWALL: 13219

before_script:
  - terraform --version
  - aws --version

stages:
  - build
  - deploy
  - firewall

tf:plan:
  tags:
    - linode
  stage: build
  script:
    - make plan
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: "tf:plan"
    paths:
      - plans/.tfplan
    reports:
      terraform: plans/tfplan.json

s3:upload:
  tags:
    - linode
  stage: build
  script:
    - make upload
  only:
    refs:
      - main

tf:apply:
  tags:
    - linode
  stage: deploy
  script:
    - make apply
  only:
    refs:
      - main
  environment:
    name: linode
    url: https://cloud.linode.com/search/?query=label:forward-proxy
    on_stop: "tf:destroy"
  dependencies:
    - "tf:plan"
  when: manual


firewall:attach:
  stage: firewall
  tags:
    - linode
  only:
    refs:
      - main
  script:
    - make attach-firewall

tf:destroy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - linode
  script:
    - make destroy
  when: manual
  environment:
    name: linode
    action: stop
  artifacts:
    name: "tf:destroy"
    paths:
      - plans/.tfdestroy
    reports:
      terraform: plans/tfdestroy.json
