variables:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: 984310022655

before_script:
  - terraform --version
  - aws --version

stages:
  - build
  - deploy:main
  - deploy:rr

tf:plan:main:
  tags:
    - linode
  stage: build
  script:
    - make plan-main
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: "tf:plan:main"
    paths:
      - main/.tfplan
    reports:
      terraform: main/tfplan.json

tf:plan:rr:
  tags:
    - linode
  stage: build
  script:
    - make plan-rr
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: "tf:plan:rr"
    paths:
      - replica/.tfplan
    reports:
      terraform: replica/tfplan.json

tf:apply:main:
  tags:
    - linode
  stage: deploy:main
  script:
    - make apply-main
  only:
    refs:
      - main
  environment:
    name: linode
    url: https://cloud.linode.com/search/?query=label:prd-main.trivialsec.com
    on_stop: "tf:destroy:main"
  dependencies:
    - "tf:plan:main"
  when: manual

tf:apply:rr:
  tags:
    - linode
  stage: deploy:rr
  script:
    - make apply-rr
  only:
    refs:
      - main
  environment:
    name: linode
    url: https://cloud.linode.com/search/?query=label:prd-rr.trivialsec.com
    on_stop: "tf:destroy:rr"
  dependencies:
    - "tf:plan:rr"
  when: manual

tf:destroy:main:
  stage: deploy:main
  variables:
    GIT_STRATEGY: none
  tags:
    - linode
  script:
    - make destroy-main
  when: manual
  environment:
    name: linode
    action: stop
  artifacts:
    name: "tf:destroy:main"
    paths:
      - main/.tfdestroy
    reports:
      terraform: main/tfdestroy.json

tf:destroy:rr:
  stage: deploy:rr
  variables:
    GIT_STRATEGY: none
  tags:
    - linode
  script:
    - make destroy-rr
  when: manual
  environment:
    name: linode
    action: stop
  artifacts:
    name: "tf:destroy:rr"
    paths:
      - replica/.tfdestroy
    reports:
      terraform: replica/tfdestroy.json
