ALTER TABLE plans DROP COLUMN `active_daily`;
ALTER TABLE plans DROP COLUMN `scheduled_active_daily`;
ALTER TABLE plans DROP COLUMN `passive_daily`;
ALTER TABLE plans DROP COLUMN `scheduled_passive_daily`;
ALTER TABLE plans DROP COLUMN `git_integration_daily`;
ALTER TABLE plans DROP COLUMN `source_code_daily`;
ALTER TABLE plans DROP COLUMN `dependency_support_rating`;
ALTER TABLE plans DROP COLUMN `alert_email`;
ALTER TABLE plans DROP COLUMN `alert_integrations`;
ALTER TABLE plans ADD COLUMN `on_demand_passive_daily` INT NOT NULL DEFAULT '10' AFTER `retention_days`;
ALTER TABLE plans ADD COLUMN `on_demand_active_daily` INT NOT NULL DEFAULT '1' AFTER `on_demand_passive_daily`;
ALTER TABLE plans ADD COLUMN `domains_monitored` INT NOT NULL DEFAULT '1' AFTER `on_demand_active_daily`;
ALTER TABLE plans ADD COLUMN `webhooks` TINYINT NOT NULL DEFAULT '0' AFTER `domains_monitored`;
ALTER TABLE plans ADD COLUMN `source_code_scans` TINYINT NOT NULL DEFAULT '0' AFTER `compromise_indicators`;
ALTER TABLE plans ADD COLUMN `compliance_reports` TINYINT NOT NULL DEFAULT '0' AFTER `source_code_scans`;